name = "glimpseOfLean"
defaultTargets = ["GlimpseOfLean"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.19.0"

[[lean_lib]]
name = "GlimpseOfLean"
